import { Background } from "../classes/Background.js";
import { CTX } from "../globals.js";
export const odds = new Array();
const oddOne = new Background(CTX, 210, 194, 35, 33, '../../assets/game/king dice/background/Odds/kd_gb_main_odds_01.png');
odds.push(oddOne);
const oddTwo = new Background(CTX, 230, 220, 36, 32, '../../assets/game/king dice/background/Odds/kd_gb_main_odds_02.png');
odds.push(oddTwo);
const oddThree = new Background(CTX, 255, 241, 38, 33, '../../assets/game/king dice/background/Odds/kd_gb_main_odds_03.png');
odds.push(oddThree);
const oddFour = new Background(CTX, 318, 273, 41, 26, '../../assets/game/king dice/background/Odds/kd_gb_main_odds_04.png');
odds.push(oddFour);
const oddFive = new Background(CTX, 355, 282, 37, 22, '../../assets/game/king dice/background/Odds/kd_gb_main_odds_05.png');
odds.push(oddFive);
const oddSix = new Background(CTX, 392, 285, 35, 20, '../../assets/game/king dice/background/Odds/kd_gb_main_odds_06.png');
odds.push(oddSix);
const oddSeven = new Background(CTX, 460, 272, 35, 25, '../../assets/game/king dice/background/Odds/kd_gb_main_odds_07.png');
odds.push(oddSeven);
const oddEight = new Background(CTX, 490, 259, 35, 28, '../../assets/game/king dice/background/Odds/kd_gb_main_odds_08.png');
odds.push(oddEight);
const oddNine = new Background(CTX, 518, 243, 34, 28, '../../assets/game/king dice/background/Odds/kd_gb_main_odds_09.png');
odds.push(oddNine);
